import { writable } from "svelte/store";

export const anim = writable("none");

export const getAnimations = () => [
  { name: "none", avatar: "None", img: null },
  ...partifulAnimations.map((t) => partifulToJukelab(t)).filter((t) => !!t),
];

export const getAnimation = (name: string) => {
  if (name === "none") {
    return { name: "none", ext: "" };
  }

  const pa = partifulAnimations.find((t) => t.name === name);
  if (pa) {
    return pa;
  }

  throw `unknown animation: ${name}`;
};

const partifulToJukelab = (t: (typeof partifulAnimations)[number]) => {
  if (t.hidden || t.name == "none") {
    return null;
  }

  return {
    name: t.name,
    avatar: null,
    img: `https://assets.getpartiful.com/backgrounds/${t.name}/thumbnail.png`,
  };
};

const partifulAnimations = [
  {
    name: "fireflies",
    ext: "mp4",
    flyerLayer: 2,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    belowContent: true,
    category: ["🔥 Trending", "🤵 Classic"],
  },
  {
    name: "winterCreatures",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🔥 Trending", "🎁 Seasonal"],
  },
  {
    name: "snowman",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "snowflakes",
    ext: "mp4",
    flyerLayer: 3,
    hasMultipleSizes: true,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    category: ["🔥 Trending", "🎁 Seasonal"],
  },
  {
    name: "gingerbread",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "christmasLights",
    ext: "mp4",
    flyerLayer: 3,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "presents",
    ext: "mp4",
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    intro: { timing: "playDuring" },
    category: ["🎁 Seasonal"],
  },
  {
    name: "gelt",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    intro: { timing: "playBefore" },
    category: ["🎁 Seasonal"],
  },
  {
    name: "flowers",
    hasMultipleSizes: true,
    ext: "mp4",
    intro: { timing: "playBefore" },
    fullScreen: true,
    flyerLayer: 1,
    pinToBottom: true,
    hidden: true,
  },
  {
    name: "casino",
    ext: "mp4",
    flyerLayer: 3,
    hasAndroidRgbGrayscale: true,
    intro: { timing: "playBefore" },
    hasMultipleSizes: true,
    fullScreen: true,
    hidden: true,
  },
  {
    hidden: true,
    name: "balloons",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasMultipleSizes: true,
    pinToBottom: true,
  },
  {
    name: "laserShow",
    ext: "mp4",
    belowContent: true,
    hasMultipleSizes: true,
    flyerLayer: 1,
    fullScreen: true,
    intro: { timing: "playDuring" },
    hidden: true,
  },
  {
    hidden: true,
    name: "holi",
    ext: "mp4",
    belowContent: true,
    flyerLayer: 3,
    fullScreen: true,
    hasMultipleSizes: true,
    intro: { timing: "playBefore" },
    pinToBottom: true,
  },
  {
    name: "beerPong",
    ext: "mp4",
    flyerLayer: 1,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    intro: { timing: "playBefore" },
    pinToBottom: true,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "spaceInvaders",
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    ext: "mp4",
    fullScreen: true,
    flyerLayer: 2,
    pinToBottom: false,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "tennis",
    intro: { timing: "playBefore" },
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    ext: "mp4",
    fullScreen: true,
    flyerLayer: 1,
    pinToBottom: true,
    category: ["⚽️ Sports"],
  },
  {
    name: "fireCannons",
    ext: "mp4",
    flyerLayer: 2,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    belowContent: true,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "graduation",
    ext: "mp4",
    flyerLayer: 1,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    intro: { timing: "playBefore" },
    pinToBottom: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "sakura",
    ext: "mp4",
    flyerLayer: 3,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    category: ["🎁 Seasonal", "🤵 Classic"],
  },
  {
    name: "sunbeams",
    ext: "mp4",
    belowContent: true,
    flyerLayer: 2,
    fullScreen: true,
    pinToBottom: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🎁 Seasonal", "🤵 Classic"],
  },
  {
    name: "bubbles",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "starrySky",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "basketball",
    intro: { timing: "playBefore" },
    hasMultipleSizes: true,
    ext: "json",
    fullScreen: true,
    pinToBottom: true,
    flyerLayer: 3,
    category: ["⚽️ Sports"],
  },
  {
    name: "beachballs",
    ext: "json",
    flyerLayer: 3,
    fullScreen: true,
    hasMultipleSizes: true,
    intro: { timing: "playDuring", introOnly: true },
    pinToBottom: true,
    category: ["⚽️ Sports"],
  },
  {
    name: "dandelions",
    ext: "json",
    flyerLayer: 3,
    hasMultipleSizes: true,
    category: ["🎁 Seasonal", "🤵 Classic"],
  },
  {
    name: "bows",
    hasMultipleSizes: true,
    ext: "mp4",
    fullScreen: true,
    pinToBottom: true,
    flyerLayer: 2,
    hasAndroidRgbGrayscale: true,
    category: ["🐒 Fun"],
  },
  {
    name: "kisses",
    hasMultipleSizes: true,
    ext: "mp4",
    fullScreen: true,
    pinToBottom: true,
    flyerLayer: 2,
    hasAndroidRgbGrayscale: true,
    category: ["🐒 Fun"],
  },
  {
    name: "lightning",
    ext: "mp4",
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🐒 Fun"],
  },
  {
    hidden: true,
    name: "cuteGhost",
    ext: "mp4",
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🐒 Fun"],
  },
  {
    name: "confettiExplosion",
    ext: "mp4",
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    intro: { timing: "playDuring" },
    belowContent: true,
    category: ["🐒 Fun"],
  },
  {
    name: "smoke",
    ext: "mp4",
    belowContent: true,
    flyerLayer: 3,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🐒 Fun", "🎁 Seasonal"],
  },
  {
    name: "confetti",
    ext: "json",
    flyerLayer: 3,
    hasBackLayer: true,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "sparkles",
    ext: "mp4",
    flyerLayer: 3,
    fullScreen: "mobile",
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "hearts",
    ext: "json",
    flyerLayer: 3,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "fireworks",
    ext: "mp4",
    flyerLayer: 1,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "cash",
    ext: "json",
    flyerLayer: 3,
    fullScreen: true,
    hasMultipleSizes: true,
    intro: { timing: "playBefore" },
    pinToBottom: true,
    category: ["🔥 Trending", "🐒 Fun"],
  },
  {
    name: "doge",
    ext: "json",
    flyerLayer: 3,
    hasMultipleSizes: true,
    category: ["🐒 Fun"],
  },
  {
    name: "disco",
    ext: "mp4",
    belowContent: true,
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "lights",
    ext: "mp4",
    belowContent: true,
    flyerLayer: 3,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🤵 Classic"],
  },
  {
    name: "stars",
    ext: "json",
    flyerLayer: 1,
    category: ["🤵 Classic"],
  },
  {
    name: "lasers",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🐒 Fun"],
  },
  {
    name: "leaves",
    ext: "mp4",
    flyerLayer: 1,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "spiders",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    intro: { timing: "playDuring" },
    category: ["🎁 Seasonal"],
  },
  {
    name: "shadowBats",
    ext: "mp4",
    flyerLayer: 3,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "football",
    ext: "json",
    flyerLayer: 1,
    fullScreen: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["⚽️ Sports"],
  },
  {
    name: "shamrock",
    fullScreen: true,
    hasMultipleSizes: true,
    ext: "json",
    flyerLayer: 3,
    category: ["🎁 Seasonal"],
  },
  {
    name: "thanksgivingFood",
    ext: "mp4",
    flyerLayer: 2,
    fullScreen: true,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    pinToBottom: true,
    category: ["🎁 Seasonal"],
  },
  {
    name: "spiderwebs",
    ext: "mp4",
    flyerLayer: 1,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    pinToBottom: false,
    category: ["🎁 Seasonal"],
  },
  {
    name: "handprints",
    ext: "mp4",
    flyerLayer: 1,
    hasAndroidRgbGrayscale: true,
    hasMultipleSizes: true,
    fullScreen: true,
    intro: { timing: "playBefore" },
    belowContent: true,
    pinToBottom: true,
    category: ["🎁 Seasonal"],
  },
  { name: "none" },
];
